# Generated by Django 5.1.1 on 2024-09-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_for_partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
