# Generated by Django 5.1.1 on 2024-09-15 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_for_partner', '0002_apartment_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('status', models.CharField(choices=[('IN_PROCESSING', 'IN_PROCESSING'), ('REJECTED', 'REJECTED'), ('ACCEPTED', 'ACCEPTED')], default='IN_PROCESSING', max_length=255, verbose_name='Статус заявки')),
                ('user_telegram_id', models.CharField(max_length=255, verbose_name='Пользователь')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Телефон')),
                ('user_username', models.CharField(max_length=255, verbose_name='Имя Пользователя')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='bot_for_partner.apartment', verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Заявка на квартиру',
                'verbose_name_plural': 'Заявки на квартиры',
            },
        ),
    ]
