# Generated by Django 5.1.1 on 2024-09-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_for_partner', '0003_apartmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
